version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: himanshu2459/dd-backend:latest
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb:27017/devopsdb
    ports:
      - "5000:5000"

  frontend:
    image: himanshu2459/dd-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000/api/tutorials
    command: >
      /bin/sh -c "
      envsubst < /usr/share/nginx/html/assets/env.js > /usr/share/nginx/html/assets/env.tmp.js &&
      mv /usr/share/nginx/html/assets/env.tmp.js /usr/share/nginx/html/assets/env.js &&
      nginx -g 'daemon off;'
      "
    ports:
      - "8080:80"

volumes:
  mongo_data:
